### ISSUE TITLE
Property 'section' not found on Object type of 'NSIndexPath *' and also 'row' in NSIndexPath category.

### ISSUE THREAD

**Issue by randikac32** [mutualmobile/MMSpreadsheetView#20]
I's not allowed to build a test project after adding the MMSpreadsheetView showing the following two errors:
![screen shot 2015-04-05 at 8 04 22 pm](https://cloud.githubusercontent.com/assets/6355848/6997190/2bcf58ac-dbcf-11e4-8bc1-6ab56f0e420a.png)
So I tried adding the following line to import UITableView because I got to know that there is a category written in UITableView to integrate with NSIndexPath.

      #import <UIKit/UITableView.h>

And my problem was resolved. Please let me know what you think.
Thanks!

**Comment by jeffla** [comment]
Those properties are part of the UIKit extension. See https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSIndexPath_UIKitAdditions/

Sounds like there's a missing <code>#import \<UIKit/UIKit.h\></code> somewhere.

**Comment by randikac32** [comment]
Hi,

Yeah, that's true! I also saw that Apples doc which you have sent me and
then wondered what's going on with my XCode don't let me to build it.
Then I added that line,
#import <UIKit/UITableView.h>
And that worked thankfully!

Thanks for you guys too for this much useful implementation!

Cheers!
