### ISSUE TITLE
Memory issue when number of column is 1. Memory reaching 5 GB within a 30 sec.

### ISSUE THREAD

**Issue by sanojKashyap** [mutualmobile/MMSpreadsheetView#25]
Just try to run the with minimum col with 1 and see memory raising like anything. Please, check it.

**Comment by jeffla** [comment]
See the readme.

```Performance: As the number of cells shown increases, scrolling performance declines. A large grid (1000x1000) takes a long time to initialize, but if the cell sizes are large enough (150x150) or greater, scrolling performance is not affected. However, a small grid (50x50) of (20x20) cells basically doesn't scroll.```

**Comment by sanojKashyap** [comment]
I used one col, it was crashing due assert statement. view wont load with 25 rows and 1 column?

**Comment by jeffla** [comment]
If you just need 1 column, use a CollectionView. This is for a grid of collectionViews.
